import type { GetStaticPropsContext, NextPage } from "next";
import { useTranslations } from "next-intl";
import { ContentfulCollection, createClient, Entry } from "contentful";

import Head from "next/head";
import Image from "next/image";
import { Blog } from "../types";
import Header from "../components/Header";
import Footer from "../components/Footer";

interface HomeProps {
  blogs: Entry<Blog>[];
}

const Home: NextPage<HomeProps> = ({ blogs }) => {
  const t = useTranslations("Home");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <h1 className="text-6xl font-bold underline">{t("title")}</h1>
        <h3>{blogs.map((blog) => blog.fields?.title)}</h3>
      </main>

      <Footer />
    </div>
  );
};

export async function getStaticProps({ locale }: GetStaticPropsContext) {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID || "",
    accessToken: process.env.CONTENTFUL_ACCESS_KEY || "",
  });
  console.log("locale", locale);

  const res = await client.getEntries<Blog>({
    content_type: "coinmenaBlog",
    locale,
  });

  return {
    props: {
      locale,
      messages: (await import(`../lang/${locale}.json`)).default,
      blogs: res.items,
    },
  };
}

export default Home;
